<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use Stripe;
class StripePaymentController extends Controller
{
    public function stripePost(Request $request)
    {
       try {

            // Set the Stripe API secret key
            Stripe\Stripe::setApiKey(env('STRIPE_SECRET'));


            // Create a charge
            $charge = Stripe\Charge::create([
                "amount" => 100 * 150,  // we will add amount accoding to the price of course
                "currency" => "usd",
                "source" => $request->stripeToken, // Token generated by Stripe in the frontend
                "description" => "Test payment via API"
            ]);
            

            // If successful, return a success response
            return response()->json([
                'success' => true,
                'message' => 'Payment successful!',
                'charge' => $charge
            ], 200);


        } catch (\Exception $e) {
            // If error occurs, return an error response
            return response()->json([
                'success' => false,
                'message' => 'Payment failed!',
                'error' => $e->getMessage()
            ], 500);
        }
    }
}